"""Smoke tests for capstone.control.baseline."""
from __future__ import annotations

import csv
import json
from pathlib import Path

import pytest

from capstone.common.logging import load
from capstone.control.baseline import (
    describe_profile,
    detect_profile,
    extract_series,
    find_action_window,
    format_gate_annotation,
    main,
    metrics_to_csv_row,
)
from capstone.control.metrics import compute_metrics


REPO = Path(__file__).resolve().parents[3]   # capstone/ at Swarm_Drones/capstone/, repo root is 3 up
LOGS = REPO / "flight_logs"
WEIGHT = LOGS / "flight_20260504_115733_WEIGHT+10.jsonl"


def _find_wind5() -> Path | None:
    """Wind5 log was renamed at one point; tolerate both forms."""
    for stem in ("flight_20260504_123507_WIND5.jsonl",
                 "flight_20260504_123507.jsonl"):
        p = LOGS / stem
        if p.exists():
            return p
    return None


WIND5 = _find_wind5() or (LOGS / "flight_20260504_123507_WIND5.jsonl")


@pytest.fixture
def wind5_log():
    if not WIND5.exists():
        pytest.skip(f"missing {WIND5}")
    return load(WIND5)


@pytest.fixture
def weight_log():
    if not WEIGHT.exists():
        pytest.skip(f"missing {WEIGHT}")
    return load(WEIGHT)


def test_profile_detected_from_event(wind5_log):
    """capstone_disturbance_active event is the authoritative source."""
    assert detect_profile(wind5_log) == "wind5"


def test_profile_detected_from_filename_when_event_absent(weight_log):
    """Filename hint maps WEIGHT+10 -> mass+10 (the user's naming != our key)."""
    assert detect_profile(weight_log) == "mass+10"


def test_extract_series_lengths_match(wind5_log):
    s = extract_series(wind5_log)
    n = len(s["t"])
    assert n == len(s["alt"]) == len(s["x"]) == len(s["y"])
    assert n == len(s["roll"]) == len(s["pitch"]) == len(s["yaw"])
    assert n == len(s["gyro_mag"])
    # wind5 log was produced after the bridge edit that adds wind_world.
    assert len(s["wind_mag"]) == n


def test_csv_row_has_all_fields(wind5_log):
    m = compute_metrics(wind5_log, "wind5")
    row = metrics_to_csv_row(m)
    expected = {
        "log_path", "profile", "duration_s", "n_state_samples",
        "window_t0", "window_t1", "window_duration_s",
        "alt_mean_m", "alt_std_m", "xy_std_m", "xy_excursion_max_m",
        "gyro_rms", "gyro_peak", "roll_std", "pitch_std",
        "crashed", "passed", "failures",
    }
    assert expected.issubset(row.keys())
    assert row["profile"] == "wind5"
    # Under uniform calm gates, wind5 fails -- 5 m/s wind pushes the drone
    # past the 5 cm position bound and the 3 deg tilt bound.
    assert row["passed"] == 0


def test_main_writes_baseline_artifacts(tmp_path):
    """End-to-end: --no-plots avoids matplotlib so the test stays fast.

    README.md is intentionally NOT generated by the tool -- the user
    hand-maintains it so their edits aren't overwritten on each run.
    """
    rc = main([str(LOGS), "--out", str(tmp_path), "--no-plots"])
    assert rc == 0
    assert (tmp_path / "baseline.csv").exists()
    assert (tmp_path / "baseline.json").exists()
    assert (tmp_path / "summary.txt").exists()
    assert not (tmp_path / "README.md").exists(), \
        "README.md should not be auto-generated -- it overwrites user edits"

    # CSV: every profile we ran must be present.
    with (tmp_path / "baseline.csv").open() as f:
        rows = list(csv.DictReader(f))
    profiles = {r["profile"] for r in rows}
    assert {"calm", "mass+10", "wind2", "wind5", "imu_noise"}.issubset(profiles), profiles


def test_main_rejects_nonfolder(tmp_path):
    bogus = tmp_path / "does_not_exist"
    assert main([str(bogus)]) == 2


def test_main_with_plots_writes_comparison_png(tmp_path):
    """Regression: comparison plot used to crash on empty-string CSV cells."""
    rc = main([str(LOGS), "--out", str(tmp_path)])
    assert rc == 0
    assert (tmp_path / "comparison.png").exists()
    assert (tmp_path / "comparison.png").stat().st_size > 0
    # Per-log plots are split across plots/full/ and plots/zoom/ subdirs.
    full_plots = list((tmp_path / "plots" / "full").glob("*.png"))
    assert len(full_plots) >= 5


def test_describe_profile_shows_wind_mass_imu():
    """Subtitle string for each profile mentions the actual disturbance values."""
    s = describe_profile("calm", 1.365)
    assert "wind: calm" in s
    assert "mass 1.365 kg (nominal)" in s
    assert "IMU clean" in s

    s = describe_profile("mass+10", 1.365)
    assert "+10%" in s
    # 1.365 * 1.10 = 1.5015
    assert "1.501" in s or "1.502" in s

    s = describe_profile("wind5", 1.365)
    # OU sigma 5/3 -> 3-sigma envelope ~5 m/s peaks (rounded by :.0f)
    assert "wind ~5 m/s peaks" in s
    assert "IMU clean" in s

    s = describe_profile("imu_noise", 1.365)
    assert "wind: calm" in s
    assert "gyro 0.02" in s
    assert "accel 0.1" in s


def test_gate_annotation_passing():
    """Gated metric well below threshold -> PASS, green edge."""
    # alt_std_m gate < 0.10 for calm; 0.04 passes.
    out = format_gate_annotation("alt_std_m", "calm", 0.04, label="alt_std")
    assert out is not None
    text, edge = out
    assert "alt_std = 0.04" in text
    assert "gate: < 0.1" in text
    assert "[PASS]" in text
    assert edge == "#7fbf7f"


def test_gate_annotation_failing():
    """Gated metric above threshold -> FAIL, red edge."""
    # alt_std_m gate < 0.10 for calm; 0.5 fails.
    out = format_gate_annotation("alt_std_m", "calm", 0.5, label="alt_std")
    assert out is not None
    text, edge = out
    assert "[FAIL]" in text
    assert edge == "#d62728"


def test_gate_annotation_no_gate_for_profile():
    """A metric not in PROFILE_GATES (e.g. pos_max_*, only diagnostic now)
    -> grey edge, '(no gate ...)' text. roll_max_rad is now diagnostic-only
    since the gates moved to RMS metrics."""
    out = format_gate_annotation("roll_max_rad", "wind5", 0.01, label="roll_max")
    assert out is not None
    text, edge = out
    assert "no gate" in text
    assert "[PASS]" not in text and "[FAIL]" not in text
    assert edge == "#bbb"


def test_gate_annotation_none_when_no_actual():
    assert format_gate_annotation("alt_std_m", "calm", None) is None


def test_describe_profile_unknown_returns_label():
    s = describe_profile("definitely_not_a_profile", 1.0)
    assert "unknown" in s


def test_action_window_brackets_airborne_portion(wind5_log):
    """Window starts ~1 s before first sample with alt > 0.2 m and ends
    ~1 s after the last such sample."""
    t0, t1 = find_action_window(wind5_log.states)
    assert t0 is not None and t1 is not None
    # Drone airborne ~58-78 s in this log; tolerate generous bounds.
    assert 50.0 < t0 < 65.0, t0
    assert 70.0 < t1 < 85.0, t1
    assert t1 > t0


def test_action_window_none_when_never_airborne():
    states = [
        {"t": float(i), "pos_ned": [0, 0, 0], "vel_ned": [0, 0, 0]}
        for i in range(5)
    ]
    t0, t1 = find_action_window(states)
    assert t0 is None and t1 is None


def test_zoom_plot_written_alongside_full_plot(tmp_path):
    """Every airborne run produces matching plots in plots/full/ and
    plots/zoom/. Logs where the drone never reached >0.2 m altitude (e.g.
    aborted takeoffs) get a full plot but no zoom -- find_action_window
    returns None for those. So zoom is a SUBSET of full, not necessarily
    equal.
    """
    rc = main([str(LOGS), "--out", str(tmp_path), "--require-event"])
    assert rc == 0
    full = sorted((tmp_path / "plots" / "full").glob("*.png"))
    zoom = sorted((tmp_path / "plots" / "zoom").glob("*.png"))
    # At least 5 of each (the original named-profile runs).
    assert len(full) >= 5, full
    assert len(zoom) >= 5, zoom
    # Every zoom plot must have a matching full plot.
    full_names = {p.name for p in full}
    zoom_names = {p.name for p in zoom}
    assert zoom_names.issubset(full_names), (full_names, zoom_names)


def test_require_event_filters_to_official_runs(tmp_path):
    """--require-event includes only logs with capstone_disturbance_active.

    Excludes the May-2 pre-bridge logs and aborted boots. Every profile is
    graded against the calm gates now -- with hardcoded PIDs, every profile
    fails (calm fails on ~9 cm north drift, disturbance profiles fail by
    larger margins). RL's target is to bring all profiles to PASS.
    """
    rc = main([str(LOGS), "--out", str(tmp_path), "--no-plots", "--require-event"])
    assert rc == 0
    with (tmp_path / "baseline.csv").open() as f:
        rows = list(csv.DictReader(f))
    profiles = set(r["profile"] for r in rows)
    # All the named profiles we've run so far should be present.
    expected_subset = {"calm", "mass+10", "wind2", "wind5", "imu_noise"}
    assert expected_subset.issubset(profiles), profiles
    # Every profile fails the calm gate under hardcoded PIDs -- that's the
    # whole point of using uniform gates.
    failed = [r["profile"] for r in rows if r["passed"] == "0"]
    assert len(failed) == len(rows), \
        f"some profiles unexpectedly pass calm gate: {[r['profile'] for r in rows if r['passed'] == '1']}"
